<Lbl>:
    font_name: 'res/fonts/source_code_pro/SourceCodePro-Medium.otf'
    size_hint_y: None
    height: 26
    color: 0, 0, 0, 1
    halign: 'left'
    valign: 'middle'
    text_size: self.size
    font_size: 15

<ResultsLbl>:
    halign: 'center'
    size_hint_y: None
    height: 28
    font_size: 16

<TitleLbl>:
    halign: 'center'
    text: '[u]'+ self.title + '[/u]'
    markup: True
    font_size: 20
